import Head from 'next/head'
import {
  Text,
  Heading,
  Image,
  Button,
  Container,
  Stack,
  Flex,
} from "@chakra-ui/react";
import NextLink from "next/link";
import PageLayout from '@/layout/PageLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sitecore Blok Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
      <Flex w="full" alignItems='center'>
        <Container>
          <Image
            mb="8"
            h="24"
            src="blok-logo.svg"
            alt="Sitecore Blok logo"
          />
          <Stack spacing="6" align="start">
            <Heading as="h1" size="xl">
              Build better products faster
            </Heading>
            <Text variant="subtle" maxW="prose">
              Blok is <NextLink href="https://www.sitecore.com">Sitecore’s</NextLink> product design system: the UI framework and style guide we use to build great apps.
              It’s publicly available, so that anyone can easily build software in the Sitecore design language.
            </Text>
            <Button as={NextLink} href="https://blok.sitecore.com/get-started">
              Get started
            </Button>
          </Stack>
          </Container>
      </Flex>
      </PageLayout>
    </>
  )
}
