import Head from 'next/head'
import {
  Text,
  Heading,
  Image,
  Button,
  Container,
  Stack,
  Flex,
} from "@chakra-ui/react";
import NextLink from "next/link";
import PageLayout from '@/layout/PageLayout';
import Hero from '@/components/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sitecore Blok Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <Hero />
      </PageLayout>
    </>
  )
}
