import Head from "next/head";
import {
Box,
  Container,
  Flex,
  ContainerProps,
  Text,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import React, { ReactNode } from "react";
import NavBar from "@/components/Navbar";
import navData from '../../data/navbar.json';

type PageProps = {
  title?: string;
  description?: string;
  children: ReactNode;
};

export default function PageLayout({ title, description, children }: PageProps) {
  return (
    <>
      <Head>
        <title>{title ?? "Sitecore Blok Next.js Starter"}</title>
        <meta name="description" content={description ?? "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexFlow="column nowrap" minH={"100vh"}>
        <NavBar navigationData={navData} zIndex={"sticky"} position="sticky" top="0" />
        <Flex flexGrow={1}>
          {children}
        </Flex>

        <Box p="4" bg={'neutral-fg'} textColor={'chakra-inverse-text'}>
            <Text>© Copyright 2023, Sitecore. All Rights Reserved</Text>
        </Box>
              
      </Flex>
    </>
  );
}
